### ISSUE TITLE
Reliquary Ticking Entity Due to Charm

### ISSUE THREAD

**Issue by ChosenArchitect** [P3pp3rF1y/Reliquary#682]
Issue thread:
https://github.com/ChosenArchitect/ChosensModdedAdventure/issues/123

**Comment by P3pp3rF1y** [comment]
This one as well as CME that also happened is fixed in the latest release available on CF https://www.curseforge.com/minecraft/mc-mods/reliquary-reincarnations/files/5253707

**Comment by ChosenArchitect** [comment]
Thanks bud will update!

**Comment by Maxi90909** [comment]
The issue is still present with horror mods like the knocker by M_Productions or mods from CEOofAutism.
